spring.application.name=journalApp

# Fix the port to 3306 and add the database name at the end
spring.datasource.url=jdbc:mysql://localhost:3306/springDB

# Add your MySQL credentials
spring.datasource.username=root
spring.datasource.password=Lovedeep@1984

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true